version: 'x.x'  

services:
  # Morow-backend service
  morow-backend:
    image: morow-backend-img
    container_name: morow-backend-container
    stdin_open: true
    tty: true
    network_mode: host
    privileged: true
    ipc: host
    environment:
      - NODE_ENV=production
      - TERM=xterm-256color
    volumes:
      # Allow shared directories between host and container
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
      - /run/pulse:/run/pulse
      # Mount devices and configuration files
      - /dev:/dev
      # - ./prisma:/roboe/app/prisma
      # - ./seeds:/roboe/app/seeds
      # - ./src:/roboe/app/src
      - ~/.ssh:/root/.ssh:ro  # Mount SSH keys if needed
      - ~/.gitconfig:/root/.gitconfig:ro  # Mount Git config if needed
    command:
      # Start the backend service
      /bin/bash -c "mkdir -p /roboe/app/logs && chmod 777 /roboe/app/logs && ./backend_start.sh && /bin/bash && cd ~/roboe/app"
