export const RobotStatus = {
  INITILIZING: 0,
  SERVOOFF: 1,
  SERVOON: 2,
  OPERATING: 3,
  TEACHING: 4,
  EMERGENCYSTOP: 5,
  RECOVERY: 6,
  PAUSE: 12,
};

export const RobotPosition = {
  NONE: 0,
  HOME: 1,
  PACKAGE: 2,
};

export const RobotLiftPosition = {
  NONE: 0,
  MIN: 1,
  MAX: 2,
};

export const EventAlarmCode = {
  NONE: 0,
  FAULT: 8,
  EMERGENCY_STOP: 10,
  EMERGENCY_STOP_RECOVER: 11,
  PROTECTION_STOP: 21,
  PROTECTION_STOP_RECOVER: 20,
  ROBOT_COLLISION: 22,
  LEFT_PALLET_LOAD_COMPLETE: 30,
  RIGHT_PALLET_LOAD_COMPLETE: 31,
  DEPALLETIZING_LOAD_COMPLETE: 32,
  BOTH_PALLET_LOAD_COMPOLETE: 33,

};

export const rosCommandCode = {
  JOB_END: 200,
  SERVOON: 203,
  SERVOOFF: 204,
  OPERATION_START: 209,
  CONTROL_OPERATION_STOP: 210,
  CONTRON_OPERATION_PAUSE: 211,
  CONTROL_OPERATION_RESUME: 212,
  CONTROL_RESET_SAFE_STOP: 213,
  CONTROL_POWER_OFF: 215,
  CONFIG_PREVIOUS_JOB_INFO: 397,
  CONFIG_BOX_INFO: 398,
  CONFIG_PALLET_INFO: 399,
  SYSTEM_POPUP_CLOSED: 5005
}

export const SenderId ={
  RPM: 2,
  CPM: 99
}

export const BOX_INSP_CD = {
  OK: 0,
  DG: 1,
  NG_INSP_NOT_DONE: 2,
  NG_NO_WGT_INSP: 3,
  NG_NO_SORT_INSP: 4,
  NG_NO_LIVE_JOB: 5,
  NG_NO_LIVE_JOB_PALLET: 6,
  NG_REGN_SPR_CD_MISMATCH: 7,
  NG_BOX_TYPE_MISMATCH: 8,
  NG_DUPLICATE_BOX: 9,
  NG_NO_BOX_FOUND: 10,
};
